# High exploration configuration
nodes: 200
lr: 0.0005  # Lower learning rate for stability
batch_size: 30
entropy_coeff: 0.05  # Higher entropy for more exploration
clip_ratio_min: 0.05  # Smaller clip ratio for more conservative updates
clip_ratio_max: 0.15
ants: 50  # More ants for better exploration
guided_exploration: true
shared_energy_norm: false  # Disable normalization
run_name: "high_exploration"
